//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MRD5
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://policja.gov.pl/MRD5Service")]
    public partial class ServiceFault
    {
        
        private string codeField;
        
        private string reasonField;
        
        private string descriptionField;
        
        private object detailsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string Reason
        {
            get
            {
                return this.reasonField;
            }
            set
            {
                this.reasonField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public string Description
        {
            get
            {
                return this.descriptionField;
            }
            set
            {
                this.descriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public object Details
        {
            get
            {
                return this.detailsField;
            }
            set
            {
                this.detailsField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://policja.gov.pl/MRD5Service")]
    public partial class ActCodeType
    {
        
        private string addToPenaltyPointsSumField;
        
        private string collisionCauseField;
        
        private string valueField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string addToPenaltyPointsSum
        {
            get
            {
                return this.addToPenaltyPointsSumField;
            }
            set
            {
                this.addToPenaltyPointsSumField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlAttributeAttribute(DataType="normalizedString")]
        public string collisionCause
        {
            get
            {
                return this.collisionCauseField;
            }
            set
            {
                this.collisionCauseField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlTextAttribute(DataType="normalizedString")]
        public string Value
        {
            get
            {
                return this.valueField;
            }
            set
            {
                this.valueField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://policja.gov.pl/MRD5Service")]
    public partial class MRD5FormRequestType
    {
        
        private MRD5FormRequestTypeQualificationDrivingDocument qualificationDrivingDocumentField;
        
        private MRD5FormRequestTypeIncidentDateAndPlace incidentDateAndPlaceField;
        
        private MRD5FormRequestTypeActDescription actDescriptionField;
        
        private MRD5FormRequestTypeActivitiesMeasures activitiesMeasuresField;
        
        private MRD5FormRequestTypeVehicle vehicleField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MRD5FormRequestTypeQualificationDrivingDocument QualificationDrivingDocument
        {
            get
            {
                return this.qualificationDrivingDocumentField;
            }
            set
            {
                this.qualificationDrivingDocumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public MRD5FormRequestTypeIncidentDateAndPlace IncidentDateAndPlace
        {
            get
            {
                return this.incidentDateAndPlaceField;
            }
            set
            {
                this.incidentDateAndPlaceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public MRD5FormRequestTypeActDescription ActDescription
        {
            get
            {
                return this.actDescriptionField;
            }
            set
            {
                this.actDescriptionField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public MRD5FormRequestTypeActivitiesMeasures ActivitiesMeasures
        {
            get
            {
                return this.activitiesMeasuresField;
            }
            set
            {
                this.activitiesMeasuresField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public MRD5FormRequestTypeVehicle Vehicle
        {
            get
            {
                return this.vehicleField;
            }
            set
            {
                this.vehicleField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://policja.gov.pl/MRD5Service")]
    public partial class MRD5FormRequestTypeQualificationDrivingDocument
    {
        
        private System.DateTime qualificationDateField;
        
        private string documentNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime QualificationDate
        {
            get
            {
                return this.qualificationDateField;
            }
            set
            {
                this.qualificationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=1)]
        public string DocumentNumber
        {
            get
            {
                return this.documentNumberField;
            }
            set
            {
                this.documentNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://policja.gov.pl/MRD5Service")]
    public partial class MRD5FormRequestTypeIncidentDateAndPlace
    {
        
        private System.DateTime incidentDateTimeField;
        
        private bool incidentDateTimeFieldSpecified;
        
        private IncidentAddressType incidentAddressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public System.DateTime IncidentDateTime
        {
            get
            {
                return this.incidentDateTimeField;
            }
            set
            {
                this.incidentDateTimeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IncidentDateTimeSpecified
        {
            get
            {
                return this.incidentDateTimeFieldSpecified;
            }
            set
            {
                this.incidentDateTimeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public IncidentAddressType IncidentAddress
        {
            get
            {
                return this.incidentAddressField;
            }
            set
            {
                this.incidentAddressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://policja.gov.pl/MRD5Service")]
    public partial class IncidentAddressType
    {
        
        private string boroughIDField;
        
        private string cityIDField;
        
        private string streetIDField;
        
        private string roadNumberField;
        
        private string roadKilometerField;
        
        private decimal coordinateXField;
        
        private bool coordinateXFieldSpecified;
        
        private decimal coordinateYField;
        
        private bool coordinateYFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string BoroughID
        {
            get
            {
                return this.boroughIDField;
            }
            set
            {
                this.boroughIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=1)]
        public string CityID
        {
            get
            {
                return this.cityIDField;
            }
            set
            {
                this.cityIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=2)]
        public string StreetID
        {
            get
            {
                return this.streetIDField;
            }
            set
            {
                this.streetIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=3)]
        public string RoadNumber
        {
            get
            {
                return this.roadNumberField;
            }
            set
            {
                this.roadNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=4)]
        public string RoadKilometer
        {
            get
            {
                return this.roadKilometerField;
            }
            set
            {
                this.roadKilometerField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=5)]
        public decimal CoordinateX
        {
            get
            {
                return this.coordinateXField;
            }
            set
            {
                this.coordinateXField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CoordinateXSpecified
        {
            get
            {
                return this.coordinateXFieldSpecified;
            }
            set
            {
                this.coordinateXFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public decimal CoordinateY
        {
            get
            {
                return this.coordinateYField;
            }
            set
            {
                this.coordinateYField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool CoordinateYSpecified
        {
            get
            {
                return this.coordinateYFieldSpecified;
            }
            set
            {
                this.coordinateYFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://policja.gov.pl/MRD5Service")]
    public partial class MRD5FormRequestTypeActDescription
    {
        
        private ActCodeType[] codeField;
        
        private MRD5FormRequestTypeActDescriptionOutOfDirectory outOfDirectoryField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("Code", Order=0)]
        public ActCodeType[] Code
        {
            get
            {
                return this.codeField;
            }
            set
            {
                this.codeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public MRD5FormRequestTypeActDescriptionOutOfDirectory OutOfDirectory
        {
            get
            {
                return this.outOfDirectoryField;
            }
            set
            {
                this.outOfDirectoryField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://policja.gov.pl/MRD5Service")]
    public enum MRD5FormRequestTypeActDescriptionOutOfDirectory
    {
        
        /// <remarks/>
        T,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://policja.gov.pl/MRD5Service")]
    public partial class MRD5FormRequestTypeActivitiesMeasures
    {
        
        private MRD5FormRequestTypeActivitiesMeasuresFineCode fineCodeField;
        
        private bool fineCodeFieldSpecified;
        
        private string fineNumberField;
        
        private decimal fineField;
        
        private bool fineFieldSpecified;
        
        private System.DateTime effectiveAdjudicationDateField;
        
        private bool effectiveAdjudicationDateFieldSpecified;
        
        private MRD5FormRequestTypeActivitiesMeasuresPreparatoryProceeding preparatoryProceedingField;
        
        private bool preparatoryProceedingFieldSpecified;
        
        private System.DateTime startProceedingsDateField;
        
        private bool startProceedingsDateFieldSpecified;
        
        private MRD5FormRequestTypeActivitiesMeasuresApplicationCourtMark applicationCourtMarkField;
        
        private bool applicationCourtMarkFieldSpecified;
        
        private MRD5FormRequestTypeActivitiesMeasuresNoPermissionMark noPermissionMarkField;
        
        private bool noPermissionMarkFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MRD5FormRequestTypeActivitiesMeasuresFineCode FineCode
        {
            get
            {
                return this.fineCodeField;
            }
            set
            {
                this.fineCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FineCodeSpecified
        {
            get
            {
                return this.fineCodeFieldSpecified;
            }
            set
            {
                this.fineCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FineNumber
        {
            get
            {
                return this.fineNumberField;
            }
            set
            {
                this.fineNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public decimal Fine
        {
            get
            {
                return this.fineField;
            }
            set
            {
                this.fineField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool FineSpecified
        {
            get
            {
                return this.fineFieldSpecified;
            }
            set
            {
                this.fineFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public System.DateTime EffectiveAdjudicationDate
        {
            get
            {
                return this.effectiveAdjudicationDateField;
            }
            set
            {
                this.effectiveAdjudicationDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EffectiveAdjudicationDateSpecified
        {
            get
            {
                return this.effectiveAdjudicationDateFieldSpecified;
            }
            set
            {
                this.effectiveAdjudicationDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public MRD5FormRequestTypeActivitiesMeasuresPreparatoryProceeding PreparatoryProceeding
        {
            get
            {
                return this.preparatoryProceedingField;
            }
            set
            {
                this.preparatoryProceedingField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PreparatoryProceedingSpecified
        {
            get
            {
                return this.preparatoryProceedingFieldSpecified;
            }
            set
            {
                this.preparatoryProceedingFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=5)]
        public System.DateTime StartProceedingsDate
        {
            get
            {
                return this.startProceedingsDateField;
            }
            set
            {
                this.startProceedingsDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartProceedingsDateSpecified
        {
            get
            {
                return this.startProceedingsDateFieldSpecified;
            }
            set
            {
                this.startProceedingsDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public MRD5FormRequestTypeActivitiesMeasuresApplicationCourtMark ApplicationCourtMark
        {
            get
            {
                return this.applicationCourtMarkField;
            }
            set
            {
                this.applicationCourtMarkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ApplicationCourtMarkSpecified
        {
            get
            {
                return this.applicationCourtMarkFieldSpecified;
            }
            set
            {
                this.applicationCourtMarkFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public MRD5FormRequestTypeActivitiesMeasuresNoPermissionMark NoPermissionMark
        {
            get
            {
                return this.noPermissionMarkField;
            }
            set
            {
                this.noPermissionMarkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool NoPermissionMarkSpecified
        {
            get
            {
                return this.noPermissionMarkFieldSpecified;
            }
            set
            {
                this.noPermissionMarkFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://policja.gov.pl/MRD5Service")]
    public enum MRD5FormRequestTypeActivitiesMeasuresFineCode
    {
        
        /// <remarks/>
        K,
        
        /// <remarks/>
        G,
        
        /// <remarks/>
        Z,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://policja.gov.pl/MRD5Service")]
    public enum MRD5FormRequestTypeActivitiesMeasuresPreparatoryProceeding
    {
        
        /// <remarks/>
        T,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://policja.gov.pl/MRD5Service")]
    public enum MRD5FormRequestTypeActivitiesMeasuresApplicationCourtMark
    {
        
        /// <remarks/>
        T,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://policja.gov.pl/MRD5Service")]
    public enum MRD5FormRequestTypeActivitiesMeasuresNoPermissionMark
    {
        
        /// <remarks/>
        T,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://policja.gov.pl/MRD5Service")]
    public partial class MRD5FormRequestTypeVehicle
    {
        
        private string vehicleTypeCodeField;
        
        private string makeTypeCodeField;
        
        private string makeSubTypeCodeField;
        
        private MRD5FormRequestTypeVehicleCountryAdministrationUnitReference countryAdministrationUnitReferenceField;
        
        private string vehicleRegistrationNumberField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string VehicleTypeCode
        {
            get
            {
                return this.vehicleTypeCodeField;
            }
            set
            {
                this.vehicleTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=1)]
        public string MakeTypeCode
        {
            get
            {
                return this.makeTypeCodeField;
            }
            set
            {
                this.makeTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=2)]
        public string MakeSubTypeCode
        {
            get
            {
                return this.makeSubTypeCodeField;
            }
            set
            {
                this.makeSubTypeCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public MRD5FormRequestTypeVehicleCountryAdministrationUnitReference CountryAdministrationUnitReference
        {
            get
            {
                return this.countryAdministrationUnitReferenceField;
            }
            set
            {
                this.countryAdministrationUnitReferenceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string VehicleRegistrationNumber
        {
            get
            {
                return this.vehicleRegistrationNumberField;
            }
            set
            {
                this.vehicleRegistrationNumberField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://policja.gov.pl/MRD5Service")]
    public partial class MRD5FormRequestTypeVehicleCountryAdministrationUnitReference
    {
        
        private string idField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ID
        {
            get
            {
                return this.idField;
            }
            set
            {
                this.idField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://policja.gov.pl/MRD5Service")]
    public partial class AddressType
    {
        
        private string cityNameField;
        
        private string streetNameField;
        
        private string buildingNumberField;
        
        private string flatNumberField;
        
        private string cityReferenceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string CityName
        {
            get
            {
                return this.cityNameField;
            }
            set
            {
                this.cityNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=1)]
        public string StreetName
        {
            get
            {
                return this.streetNameField;
            }
            set
            {
                this.streetNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=2)]
        public string BuildingNumber
        {
            get
            {
                return this.buildingNumberField;
            }
            set
            {
                this.buildingNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=3)]
        public string FlatNumber
        {
            get
            {
                return this.flatNumberField;
            }
            set
            {
                this.flatNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=4)]
        public string CityReference
        {
            get
            {
                return this.cityReferenceField;
            }
            set
            {
                this.cityReferenceField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://policja.gov.pl/MRD5Service")]
    public partial class PersonFormRequestType
    {
        
        private PersonFormRequestTypePersonIdentityRecord personIdentityRecordField;
        
        private PersonFormRequestTypePersonCitizenshipRecord personCitizenshipRecordField;
        
        private PersonFormRequestTypePersonAddressRecord personAddressRecordField;
        
        private PersonFormRequestTypePersonDocumentRecord personDocumentRecordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PersonFormRequestTypePersonIdentityRecord PersonIdentityRecord
        {
            get
            {
                return this.personIdentityRecordField;
            }
            set
            {
                this.personIdentityRecordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public PersonFormRequestTypePersonCitizenshipRecord PersonCitizenshipRecord
        {
            get
            {
                return this.personCitizenshipRecordField;
            }
            set
            {
                this.personCitizenshipRecordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public PersonFormRequestTypePersonAddressRecord PersonAddressRecord
        {
            get
            {
                return this.personAddressRecordField;
            }
            set
            {
                this.personAddressRecordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public PersonFormRequestTypePersonDocumentRecord PersonDocumentRecord
        {
            get
            {
                return this.personDocumentRecordField;
            }
            set
            {
                this.personDocumentRecordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://policja.gov.pl/MRD5Service")]
    public partial class PersonFormRequestTypePersonIdentityRecord
    {
        
        private string familyNameField;
        
        private string firstNameField;
        
        private PersonFormRequestTypePersonIdentityRecordPersonEntryCode personEntryCodeField;
        
        private bool personEntryCodeFieldSpecified;
        
        private PersonFormRequestTypePersonIdentityRecordGenderCode genderCodeField;
        
        private bool genderCodeFieldSpecified;
        
        private string pESELNumberField;
        
        private System.DateTime birthDateField;
        
        private string fathersNameField;
        
        private string mothersNameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string FamilyName
        {
            get
            {
                return this.familyNameField;
            }
            set
            {
                this.familyNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string FirstName
        {
            get
            {
                return this.firstNameField;
            }
            set
            {
                this.firstNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public PersonFormRequestTypePersonIdentityRecordPersonEntryCode PersonEntryCode
        {
            get
            {
                return this.personEntryCodeField;
            }
            set
            {
                this.personEntryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool PersonEntryCodeSpecified
        {
            get
            {
                return this.personEntryCodeFieldSpecified;
            }
            set
            {
                this.personEntryCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public PersonFormRequestTypePersonIdentityRecordGenderCode GenderCode
        {
            get
            {
                return this.genderCodeField;
            }
            set
            {
                this.genderCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool GenderCodeSpecified
        {
            get
            {
                return this.genderCodeFieldSpecified;
            }
            set
            {
                this.genderCodeFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public string PESELNumber
        {
            get
            {
                return this.pESELNumberField;
            }
            set
            {
                this.pESELNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=5)]
        public System.DateTime BirthDate
        {
            get
            {
                return this.birthDateField;
            }
            set
            {
                this.birthDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=6)]
        public string FathersName
        {
            get
            {
                return this.fathersNameField;
            }
            set
            {
                this.fathersNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=7)]
        public string MothersName
        {
            get
            {
                return this.mothersNameField;
            }
            set
            {
                this.mothersNameField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://policja.gov.pl/MRD5Service")]
    public enum PersonFormRequestTypePersonIdentityRecordPersonEntryCode
    {
        
        /// <remarks/>
        O,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://policja.gov.pl/MRD5Service")]
    public enum PersonFormRequestTypePersonIdentityRecordGenderCode
    {
        
        /// <remarks/>
        K,
        
        /// <remarks/>
        M,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://policja.gov.pl/MRD5Service")]
    public partial class PersonFormRequestTypePersonCitizenshipRecord
    {
        
        private System.DateTime startDateField;
        
        private bool startDateFieldSpecified;
        
        private string sOBYCodeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime StartDate
        {
            get
            {
                return this.startDateField;
            }
            set
            {
                this.startDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool StartDateSpecified
        {
            get
            {
                return this.startDateFieldSpecified;
            }
            set
            {
                this.startDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=1)]
        public string SOBYCode
        {
            get
            {
                return this.sOBYCodeField;
            }
            set
            {
                this.sOBYCodeField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://policja.gov.pl/MRD5Service")]
    public partial class PersonFormRequestTypePersonAddressRecord
    {
        
        private System.DateTime effectiveDateField;
        
        private bool effectiveDateFieldSpecified;
        
        private string sRADCodeField;
        
        private AddressType addressField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=0)]
        public System.DateTime EffectiveDate
        {
            get
            {
                return this.effectiveDateField;
            }
            set
            {
                this.effectiveDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool EffectiveDateSpecified
        {
            get
            {
                return this.effectiveDateFieldSpecified;
            }
            set
            {
                this.effectiveDateFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=1)]
        public string SRADCode
        {
            get
            {
                return this.sRADCodeField;
            }
            set
            {
                this.sRADCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public AddressType Address
        {
            get
            {
                return this.addressField;
            }
            set
            {
                this.addressField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://policja.gov.pl/MRD5Service")]
    public partial class PersonFormRequestTypePersonDocumentRecord
    {
        
        private string zORZCodeField;
        
        private string itemCategoryCodeField;
        
        private object documentNumberField;
        
        private PersonFormRequestTypePersonDocumentRecordDuplicateMark duplicateMarkField;
        
        private bool duplicateMarkFieldSpecified;
        
        private string blankNumberField;
        
        private string issuingAuthorityField;
        
        private PersonFormRequestTypePersonDocumentRecordVehicleLicenceCode[] drivingLicenceCodesField;
        
        private System.DateTime issuingDateField;
        
        private bool issuingDateFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string ZORZCode
        {
            get
            {
                return this.zORZCodeField;
            }
            set
            {
                this.zORZCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ItemCategoryCode
        {
            get
            {
                return this.itemCategoryCodeField;
            }
            set
            {
                this.itemCategoryCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public object DocumentNumber
        {
            get
            {
                return this.documentNumberField;
            }
            set
            {
                this.documentNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=3)]
        public PersonFormRequestTypePersonDocumentRecordDuplicateMark DuplicateMark
        {
            get
            {
                return this.duplicateMarkField;
            }
            set
            {
                this.duplicateMarkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool DuplicateMarkSpecified
        {
            get
            {
                return this.duplicateMarkFieldSpecified;
            }
            set
            {
                this.duplicateMarkFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=4)]
        public string BlankNumber
        {
            get
            {
                return this.blankNumberField;
            }
            set
            {
                this.blankNumberField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=5)]
        public string IssuingAuthority
        {
            get
            {
                return this.issuingAuthorityField;
            }
            set
            {
                this.issuingAuthorityField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayAttribute(Order=6)]
        [System.Xml.Serialization.XmlArrayItemAttribute("VehicleLicenceCode", IsNullable=false)]
        public PersonFormRequestTypePersonDocumentRecordVehicleLicenceCode[] DrivingLicenceCodes
        {
            get
            {
                return this.drivingLicenceCodesField;
            }
            set
            {
                this.drivingLicenceCodesField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="date", Order=7)]
        public System.DateTime IssuingDate
        {
            get
            {
                return this.issuingDateField;
            }
            set
            {
                this.issuingDateField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool IssuingDateSpecified
        {
            get
            {
                return this.issuingDateFieldSpecified;
            }
            set
            {
                this.issuingDateFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://policja.gov.pl/MRD5Service")]
    public enum PersonFormRequestTypePersonDocumentRecordDuplicateMark
    {
        
        /// <remarks/>
        T,
        
        /// <remarks/>
        N,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://policja.gov.pl/MRD5Service")]
    public enum PersonFormRequestTypePersonDocumentRecordVehicleLicenceCode
    {
        
        /// <remarks/>
        A,
        
        /// <remarks/>
        A1,
        
        /// <remarks/>
        A2,
        
        /// <remarks/>
        AM,
        
        /// <remarks/>
        B,
        
        /// <remarks/>
        B1,
        
        /// <remarks/>
        BE,
        
        /// <remarks/>
        C,
        
        /// <remarks/>
        C1,
        
        /// <remarks/>
        C1E,
        
        /// <remarks/>
        CE,
        
        /// <remarks/>
        D,
        
        /// <remarks/>
        D1,
        
        /// <remarks/>
        D1E,
        
        /// <remarks/>
        DE,
        
        /// <remarks/>
        T,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://policja.gov.pl/MRD5Service", ConfigurationName="MRD5.ptMRD5Service")]
    public interface ptMRD5Service
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="opRejestracjaMRD5", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(MRD5.ServiceFault), Action="opRejestracjaMRD5", Name="ServiceFault")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<MRD5.opRejestracjaMRD5Response> opRejestracjaMRD5Async(MRD5.opRejestracjaMRD5Request request);
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://policja.gov.pl/MRD5Service")]
    public partial class MRD5Request
    {
        
        private MRD5RequestRequestHeader requestHeaderField;
        
        private MRD5RequestRequestBody requestBodyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MRD5RequestRequestHeader RequestHeader
        {
            get
            {
                return this.requestHeaderField;
            }
            set
            {
                this.requestHeaderField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public MRD5RequestRequestBody RequestBody
        {
            get
            {
                return this.requestBodyField;
            }
            set
            {
                this.requestBodyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://policja.gov.pl/MRD5Service")]
    public partial class MRD5RequestRequestHeader
    {
        
        private string requestIDField;
        
        private System.DateTime timestampField;
        
        private MRD5RequestRequestHeaderAuditRecord auditRecordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string RequestID
        {
            get
            {
                return this.requestIDField;
            }
            set
            {
                this.requestIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public System.DateTime Timestamp
        {
            get
            {
                return this.timestampField;
            }
            set
            {
                this.timestampField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=2)]
        public MRD5RequestRequestHeaderAuditRecord AuditRecord
        {
            get
            {
                return this.auditRecordField;
            }
            set
            {
                this.auditRecordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://policja.gov.pl/MRD5Service")]
    public partial class MRD5RequestRequestHeaderAuditRecord
    {
        
        private SystemType systemNameField;
        
        private string applicationNameField;
        
        private string moduleNameField;
        
        private string terminalNameField;
        
        private MRD5RequestRequestHeaderAuditRecordUserProfile userProfileField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public SystemType SystemName
        {
            get
            {
                return this.systemNameField;
            }
            set
            {
                this.systemNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=1)]
        public string ApplicationName
        {
            get
            {
                return this.applicationNameField;
            }
            set
            {
                this.applicationNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=2)]
        public string ModuleName
        {
            get
            {
                return this.moduleNameField;
            }
            set
            {
                this.moduleNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=3)]
        public string TerminalName
        {
            get
            {
                return this.terminalNameField;
            }
            set
            {
                this.terminalNameField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=4)]
        public MRD5RequestRequestHeaderAuditRecordUserProfile UserProfile
        {
            get
            {
                return this.userProfileField;
            }
            set
            {
                this.userProfileField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://policja.gov.pl/MRD5Service")]
    public enum SystemType
    {
        
        /// <remarks/>
        CANARD,
        
        /// <remarks/>
        GITD,
        
        /// <remarks/>
        ŻW,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://policja.gov.pl/MRD5Service")]
    public partial class MRD5RequestRequestHeaderAuditRecordUserProfile
    {
        
        private string userIDField;
        
        private string unitIDField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=0)]
        public string UserID
        {
            get
            {
                return this.userIDField;
            }
            set
            {
                this.userIDField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(DataType="normalizedString", Order=1)]
        public string UnitID
        {
            get
            {
                return this.unitIDField;
            }
            set
            {
                this.unitIDField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://policja.gov.pl/MRD5Service")]
    public partial class MRD5RequestRequestBody
    {
        
        private PersonFormRequestType personRecordField;
        
        private MRD5FormRequestType mRD5RecordField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public PersonFormRequestType PersonRecord
        {
            get
            {
                return this.personRecordField;
            }
            set
            {
                this.personRecordField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public MRD5FormRequestType MRD5Record
        {
            get
            {
                return this.mRD5RecordField;
            }
            set
            {
                this.mRD5RecordField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://policja.gov.pl/MRD5Service")]
    public partial class MRD5Response
    {
        
        private MRD5ResponseMRD5RegistrationStatus mRD5RegistrationStatusField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public MRD5ResponseMRD5RegistrationStatus MRD5RegistrationStatus
        {
            get
            {
                return this.mRD5RegistrationStatusField;
            }
            set
            {
                this.mRD5RegistrationStatusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://policja.gov.pl/MRD5Service")]
    public partial class MRD5ResponseMRD5RegistrationStatus
    {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("BusinessID", typeof(string), Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("Error", typeof(MRD5ResponseMRD5RegistrationStatusError), Order=0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true, Namespace="http://policja.gov.pl/MRD5Service")]
    public partial class MRD5ResponseMRD5RegistrationStatusError
    {
        
        private string errorCodeField;
        
        private string errorDescriptionField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=0)]
        public string ErrorCode
        {
            get
            {
                return this.errorCodeField;
            }
            set
            {
                this.errorCodeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Order=1)]
        public string ErrorDescription
        {
            get
            {
                return this.errorDescriptionField;
            }
            set
            {
                this.errorDescriptionField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class opRejestracjaMRD5Request
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://policja.gov.pl/MRD5Service", Order=0)]
        public MRD5.MRD5Request MRD5Request;
        
        public opRejestracjaMRD5Request()
        {
        }
        
        public opRejestracjaMRD5Request(MRD5.MRD5Request MRD5Request)
        {
            this.MRD5Request = MRD5Request;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class opRejestracjaMRD5Response
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://policja.gov.pl/MRD5Service", Order=0)]
        public MRD5.MRD5Response MRD5Response;
        
        public opRejestracjaMRD5Response()
        {
        }
        
        public opRejestracjaMRD5Response(MRD5.MRD5Response MRD5Response)
        {
            this.MRD5Response = MRD5Response;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface ptMRD5ServiceChannel : MRD5.ptMRD5Service, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class ptMRD5ServiceClient : System.ServiceModel.ClientBase<MRD5.ptMRD5Service>, MRD5.ptMRD5Service
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public ptMRD5ServiceClient() : 
                base(ptMRD5ServiceClient.GetDefaultBinding(), ptMRD5ServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.prMRD5ServicePort.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ptMRD5ServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(ptMRD5ServiceClient.GetBindingForEndpoint(endpointConfiguration), ptMRD5ServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ptMRD5ServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(ptMRD5ServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ptMRD5ServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(ptMRD5ServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public ptMRD5ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<MRD5.opRejestracjaMRD5Response> MRD5.ptMRD5Service.opRejestracjaMRD5Async(MRD5.opRejestracjaMRD5Request request)
        {
            return base.Channel.opRejestracjaMRD5Async(request);
        }
        
        public System.Threading.Tasks.Task<MRD5.opRejestracjaMRD5Response> opRejestracjaMRD5Async(MRD5.MRD5Request MRD5Request)
        {
            MRD5.opRejestracjaMRD5Request inValue = new MRD5.opRejestracjaMRD5Request();
            inValue.MRD5Request = MRD5Request;
            return ((MRD5.ptMRD5Service)(this)).opRejestracjaMRD5Async(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.prMRD5ServicePort))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.prMRD5ServicePort))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:9004/GITD/MRD5Service");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return ptMRD5ServiceClient.GetBindingForEndpoint(EndpointConfiguration.prMRD5ServicePort);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return ptMRD5ServiceClient.GetEndpointAddress(EndpointConfiguration.prMRD5ServicePort);
        }
        
        public enum EndpointConfiguration
        {
            
            prMRD5ServicePort,
        }
    }
}
