//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UpKi.Reference
{
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://exceptions.api.cepik.coi.gov.pl")]
    public partial class Komunikat
    {
        
        private TypKomunikatu typField;
        
        private string kodField;
        
        private string komunikatField;
        
        private string szczegolyField;
        
        private string identyfikatorBleduField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public TypKomunikatu typ
        {
            get
            {
                return this.typField;
            }
            set
            {
                this.typField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string kod
        {
            get
            {
                return this.kodField;
            }
            set
            {
                this.kodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string komunikat
        {
            get
            {
                return this.komunikatField;
            }
            set
            {
                this.komunikatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string szczegoly
        {
            get
            {
                return this.szczegolyField;
            }
            set
            {
                this.szczegolyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string identyfikatorBledu
        {
            get
            {
                return this.identyfikatorBleduField;
            }
            set
            {
                this.identyfikatorBleduField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://exceptions.api.cepik.coi.gov.pl")]
    public enum TypKomunikatu
    {
        
        /// <remarks/>
        ERROR,
        
        /// <remarks/>
        WARN,
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uprawnieniakierowcow-na-date-zu.tru.api.cepik.coi.gov.pl")]
    public partial class KomunikatBiznesowy
    {
        
        private string kodField;
        
        private string opisField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string kod
        {
            get
            {
                return this.kodField;
            }
            set
            {
                this.kodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string opis
        {
            get
            {
                return this.opisField;
            }
            set
            {
                this.opisField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uprawnieniakierowcow-na-date-zu.tru.api.cepik.coi.gov.pl")]
    public partial class DaneZakazuCofniecia
    {
        
        private string typZdarzeniaField;
        
        private System.DateTime dataDoField;
        
        private bool dataDoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string typZdarzenia
        {
            get
            {
                return this.typZdarzeniaField;
            }
            set
            {
                this.typZdarzeniaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=1)]
        public System.DateTime dataDo
        {
            get
            {
                return this.dataDoField;
            }
            set
            {
                this.dataDoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataDoSpecified
        {
            get
            {
                return this.dataDoFieldSpecified;
            }
            set
            {
                this.dataDoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uprawnieniakierowcow-na-date-zu.tru.api.cepik.coi.gov.pl")]
    public partial class DaneUprawnieniaKategorii
    {
        
        private WartoscSlownikowa kategoriaField;
        
        private System.DateTime dataWaznosciField;
        
        private bool dataWaznosciFieldSpecified;
        
        private System.DateTime dataWydaniaField;
        
        private bool dataWydaniaFieldSpecified;
        
        private DaneZakazuCofniecia[] daneZakazuCofnieciaField;
        
        private Ograniczenie[] ograniczenieField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public WartoscSlownikowa kategoria
        {
            get
            {
                return this.kategoriaField;
            }
            set
            {
                this.kategoriaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=1)]
        public System.DateTime dataWaznosci
        {
            get
            {
                return this.dataWaznosciField;
            }
            set
            {
                this.dataWaznosciField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataWaznosciSpecified
        {
            get
            {
                return this.dataWaznosciFieldSpecified;
            }
            set
            {
                this.dataWaznosciFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=2)]
        public System.DateTime dataWydania
        {
            get
            {
                return this.dataWydaniaField;
            }
            set
            {
                this.dataWydaniaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataWydaniaSpecified
        {
            get
            {
                return this.dataWydaniaFieldSpecified;
            }
            set
            {
                this.dataWydaniaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("daneZakazuCofniecia", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public DaneZakazuCofniecia[] daneZakazuCofniecia
        {
            get
            {
                return this.daneZakazuCofnieciaField;
            }
            set
            {
                this.daneZakazuCofnieciaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ograniczenie", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public Ograniczenie[] ograniczenie
        {
            get
            {
                return this.ograniczenieField;
            }
            set
            {
                this.ograniczenieField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uprawnieniakierowcow-na-date-zu.tru.api.cepik.coi.gov.pl")]
    public partial class WartoscSlownikowa
    {
        
        private string kodField;
        
        private string wartoscOpisowaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string kod
        {
            get
            {
                return this.kodField;
            }
            set
            {
                this.kodField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string wartoscOpisowa
        {
            get
            {
                return this.wartoscOpisowaField;
            }
            set
            {
                this.wartoscOpisowaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uprawnieniakierowcow-na-date-zu.tru.api.cepik.coi.gov.pl")]
    public partial class Ograniczenie
    {
        
        private string kodOgraniczeniaField;
        
        private string wartoscOgraniczeniaField;
        
        private string opisKoduField;
        
        private System.DateTime dataDoField;
        
        private bool dataDoFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string kodOgraniczenia
        {
            get
            {
                return this.kodOgraniczeniaField;
            }
            set
            {
                this.kodOgraniczeniaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string wartoscOgraniczenia
        {
            get
            {
                return this.wartoscOgraniczeniaField;
            }
            set
            {
                this.wartoscOgraniczeniaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string opisKodu
        {
            get
            {
                return this.opisKoduField;
            }
            set
            {
                this.opisKoduField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=3)]
        public System.DateTime dataDo
        {
            get
            {
                return this.dataDoField;
            }
            set
            {
                this.dataDoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataDoSpecified
        {
            get
            {
                return this.dataDoFieldSpecified;
            }
            set
            {
                this.dataDoFieldSpecified = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uprawnieniakierowcow-na-date-zu.tru.api.cepik.coi.gov.pl")]
    public partial class Ulica
    {
        
        private WartoscSlownikowa cechaUlicyField;
        
        private string kodUlicyField;
        
        private string nazwaUlicyField;
        
        private string nazwaUlicyZDokumentuField;
        
        private string nrDomuField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public WartoscSlownikowa cechaUlicy
        {
            get
            {
                return this.cechaUlicyField;
            }
            set
            {
                this.cechaUlicyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string kodUlicy
        {
            get
            {
                return this.kodUlicyField;
            }
            set
            {
                this.kodUlicyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nazwaUlicy
        {
            get
            {
                return this.nazwaUlicyField;
            }
            set
            {
                this.nazwaUlicyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string nazwaUlicyZDokumentu
        {
            get
            {
                return this.nazwaUlicyZDokumentuField;
            }
            set
            {
                this.nazwaUlicyZDokumentuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nrDomu
        {
            get
            {
                return this.nrDomuField;
            }
            set
            {
                this.nrDomuField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uprawnieniakierowcow-na-date-zu.tru.api.cepik.coi.gov.pl")]
    public partial class MiejscowoscPodstawowa
    {
        
        private string kodMiejscowosciPodstawowejField;
        
        private string nazwaMiejscowosciPodstawowejField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string kodMiejscowosciPodstawowej
        {
            get
            {
                return this.kodMiejscowosciPodstawowejField;
            }
            set
            {
                this.kodMiejscowosciPodstawowejField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string NazwaMiejscowosciPodstawowej
        {
            get
            {
                return this.nazwaMiejscowosciPodstawowejField;
            }
            set
            {
                this.nazwaMiejscowosciPodstawowejField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uprawnieniakierowcow-na-date-zu.tru.api.cepik.coi.gov.pl")]
    public partial class Miejsce
    {
        
        private string kodTERYTField;
        
        private string kodWojewodztwaField;
        
        private string nazwaWojewodztwaStanuField;
        
        private string kodPowiatuField;
        
        private string nazwaPowiatuDzielnicyField;
        
        private string kodGminyField;
        
        private string nazwaGminyField;
        
        private string kodRodzajuGminyField;
        
        private string kodPocztowyKrajowyField;
        
        private string kodMiejscowosciField;
        
        private string nazwaMiejscowosciField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string kodTERYT
        {
            get
            {
                return this.kodTERYTField;
            }
            set
            {
                this.kodTERYTField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string kodWojewodztwa
        {
            get
            {
                return this.kodWojewodztwaField;
            }
            set
            {
                this.kodWojewodztwaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nazwaWojewodztwaStanu
        {
            get
            {
                return this.nazwaWojewodztwaStanuField;
            }
            set
            {
                this.nazwaWojewodztwaStanuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string kodPowiatu
        {
            get
            {
                return this.kodPowiatuField;
            }
            set
            {
                this.kodPowiatuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string nazwaPowiatuDzielnicy
        {
            get
            {
                return this.nazwaPowiatuDzielnicyField;
            }
            set
            {
                this.nazwaPowiatuDzielnicyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public string kodGminy
        {
            get
            {
                return this.kodGminyField;
            }
            set
            {
                this.kodGminyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public string nazwaGminy
        {
            get
            {
                return this.nazwaGminyField;
            }
            set
            {
                this.nazwaGminyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public string kodRodzajuGminy
        {
            get
            {
                return this.kodRodzajuGminyField;
            }
            set
            {
                this.kodRodzajuGminyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public string kodPocztowyKrajowy
        {
            get
            {
                return this.kodPocztowyKrajowyField;
            }
            set
            {
                this.kodPocztowyKrajowyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public string kodMiejscowosci
        {
            get
            {
                return this.kodMiejscowosciField;
            }
            set
            {
                this.kodMiejscowosciField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public string nazwaMiejscowosci
        {
            get
            {
                return this.nazwaMiejscowosciField;
            }
            set
            {
                this.nazwaMiejscowosciField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uprawnieniakierowcow-na-date-zu.tru.api.cepik.coi.gov.pl")]
    public partial class Adres
    {
        
        private Miejsce miejsceField;
        
        private string nrLokaluField;
        
        private MiejscowoscPodstawowa miejscowoscPodstawowaField;
        
        private WartoscSlownikowa krajField;
        
        private Ulica ulicaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public Miejsce miejsce
        {
            get
            {
                return this.miejsceField;
            }
            set
            {
                this.miejsceField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nrLokalu
        {
            get
            {
                return this.nrLokaluField;
            }
            set
            {
                this.nrLokaluField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public MiejscowoscPodstawowa miejscowoscPodstawowa
        {
            get
            {
                return this.miejscowoscPodstawowaField;
            }
            set
            {
                this.miejscowoscPodstawowaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public WartoscSlownikowa kraj
        {
            get
            {
                return this.krajField;
            }
            set
            {
                this.krajField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public Ulica ulica
        {
            get
            {
                return this.ulicaField;
            }
            set
            {
                this.ulicaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uprawnieniakierowcow-na-date-zu.tru.api.cepik.coi.gov.pl")]
    public partial class DaneKierowcy
    {
        
        private string numerPeselField;
        
        private string imiePierwszeField;
        
        private string nazwiskoField;
        
        private System.DateTime dataUrodzeniaField;
        
        private bool dataUrodzeniaFieldSpecified;
        
        private string miejsceUrodzeniaField;
        
        private Adres adresField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string numerPesel
        {
            get
            {
                return this.numerPeselField;
            }
            set
            {
                this.numerPeselField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string imiePierwsze
        {
            get
            {
                return this.imiePierwszeField;
            }
            set
            {
                this.imiePierwszeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string nazwisko
        {
            get
            {
                return this.nazwiskoField;
            }
            set
            {
                this.nazwiskoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=3)]
        public System.DateTime dataUrodzenia
        {
            get
            {
                return this.dataUrodzeniaField;
            }
            set
            {
                this.dataUrodzeniaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataUrodzeniaSpecified
        {
            get
            {
                return this.dataUrodzeniaFieldSpecified;
            }
            set
            {
                this.dataUrodzeniaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public string miejsceUrodzenia
        {
            get
            {
                return this.miejsceUrodzeniaField;
            }
            set
            {
                this.miejsceUrodzeniaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public Adres adres
        {
            get
            {
                return this.adresField;
            }
            set
            {
                this.adresField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uprawnieniakierowcow-na-date-zu.tru.api.cepik.coi.gov.pl")]
    public partial class ParametrOsobaId
    {
        
        private long osobaIdField;
        
        private bool osobaIdFieldSpecified;
        
        private long wariantIdField;
        
        private bool wariantIdFieldSpecified;
        
        private string tokenKierowcyField;
        
        private string idkField;
        
        private DaneKierowcy daneKierowcyField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public long osobaId
        {
            get
            {
                return this.osobaIdField;
            }
            set
            {
                this.osobaIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool osobaIdSpecified
        {
            get
            {
                return this.osobaIdFieldSpecified;
            }
            set
            {
                this.osobaIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public long wariantId
        {
            get
            {
                return this.wariantIdField;
            }
            set
            {
                this.wariantIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool wariantIdSpecified
        {
            get
            {
                return this.wariantIdFieldSpecified;
            }
            set
            {
                this.wariantIdFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string tokenKierowcy
        {
            get
            {
                return this.tokenKierowcyField;
            }
            set
            {
                this.tokenKierowcyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public string idk
        {
            get
            {
                return this.idkField;
            }
            set
            {
                this.idkField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public DaneKierowcy daneKierowcy
        {
            get
            {
                return this.daneKierowcyField;
            }
            set
            {
                this.daneKierowcyField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uprawnieniakierowcow-na-date-zu.tru.api.cepik.coi.gov.pl")]
    public partial class DokumentUprawnieniaKierowcy
    {
        
        private WartoscSlownikowa typDokumentuField;
        
        private string numerDokumentuField;
        
        private string seriaNumerDokumentuField;
        
        private WartoscSlownikowa organWydajacyDokumentField;
        
        private System.DateTime dataWaznosciField;
        
        private bool dataWaznosciFieldSpecified;
        
        private System.DateTime dataWydaniaField;
        
        private bool dataWydaniaFieldSpecified;
        
        private ParametrOsobaId parametrOsobaIdField;
        
        private WartoscSlownikowa stanDokumentuField;
        
        private Ograniczenie[] ograniczenieField;
        
        private DaneUprawnieniaKategorii[] daneUprawnieniaKategoriiField;
        
        private KomunikatBiznesowy komunikatyBiznesoweField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public WartoscSlownikowa typDokumentu
        {
            get
            {
                return this.typDokumentuField;
            }
            set
            {
                this.typDokumentuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string numerDokumentu
        {
            get
            {
                return this.numerDokumentuField;
            }
            set
            {
                this.numerDokumentuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string seriaNumerDokumentu
        {
            get
            {
                return this.seriaNumerDokumentuField;
            }
            set
            {
                this.seriaNumerDokumentuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public WartoscSlownikowa organWydajacyDokument
        {
            get
            {
                return this.organWydajacyDokumentField;
            }
            set
            {
                this.organWydajacyDokumentField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=4)]
        public System.DateTime dataWaznosci
        {
            get
            {
                return this.dataWaznosciField;
            }
            set
            {
                this.dataWaznosciField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataWaznosciSpecified
        {
            get
            {
                return this.dataWaznosciFieldSpecified;
            }
            set
            {
                this.dataWaznosciFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=5)]
        public System.DateTime dataWydania
        {
            get
            {
                return this.dataWydaniaField;
            }
            set
            {
                this.dataWydaniaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool dataWydaniaSpecified
        {
            get
            {
                return this.dataWydaniaFieldSpecified;
            }
            set
            {
                this.dataWydaniaFieldSpecified = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=6)]
        public ParametrOsobaId parametrOsobaId
        {
            get
            {
                return this.parametrOsobaIdField;
            }
            set
            {
                this.parametrOsobaIdField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=7)]
        public WartoscSlownikowa stanDokumentu
        {
            get
            {
                return this.stanDokumentuField;
            }
            set
            {
                this.stanDokumentuField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ograniczenie", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=8)]
        public Ograniczenie[] ograniczenie
        {
            get
            {
                return this.ograniczenieField;
            }
            set
            {
                this.ograniczenieField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("daneUprawnieniaKategorii", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=9)]
        public DaneUprawnieniaKategorii[] daneUprawnieniaKategorii
        {
            get
            {
                return this.daneUprawnieniaKategoriiField;
            }
            set
            {
                this.daneUprawnieniaKategoriiField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=10)]
        public KomunikatBiznesowy komunikatyBiznesowe
        {
            get
            {
                return this.komunikatyBiznesoweField;
            }
            set
            {
                this.komunikatyBiznesoweField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uprawnieniakierowcow-na-date-zu.tru.api.cepik.coi.gov.pl")]
    public partial class DaneDokumentuResponse
    {
        
        private DokumentUprawnieniaKierowcy[] dokumentUprawnieniaKierowcyField;
        
        private string komunikatField;
        
        private System.DateTime dataZapytaniaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("dokumentUprawnieniaKierowcy", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public DokumentUprawnieniaKierowcy[] dokumentUprawnieniaKierowcy
        {
            get
            {
                return this.dokumentUprawnieniaKierowcyField;
            }
            set
            {
                this.dokumentUprawnieniaKierowcyField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string komunikat
        {
            get
            {
                return this.komunikatField;
            }
            set
            {
                this.komunikatField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=2)]
        public System.DateTime dataZapytania
        {
            get
            {
                return this.dataZapytaniaField;
            }
            set
            {
                this.dataZapytaniaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uprawnieniakierowcow-na-date-zu.tru.api.cepik.coi.gov.pl")]
    public partial class DaneOsoby
    {
        
        private string imiePierwszeField;
        
        private string nazwiskoField;
        
        private System.DateTime dataUrodzeniaField;
        
        private System.DateTime dataZapytaniaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string imiePierwsze
        {
            get
            {
                return this.imiePierwszeField;
            }
            set
            {
                this.imiePierwszeField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string nazwisko
        {
            get
            {
                return this.nazwiskoField;
            }
            set
            {
                this.nazwiskoField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=2)]
        public System.DateTime dataUrodzenia
        {
            get
            {
                return this.dataUrodzeniaField;
            }
            set
            {
                this.dataUrodzeniaField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=3)]
        public System.DateTime dataZapytania
        {
            get
            {
                return this.dataZapytaniaField;
            }
            set
            {
                this.dataZapytaniaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uprawnieniakierowcow-na-date-zu.tru.api.cepik.coi.gov.pl")]
    public partial class DanePesel
    {
        
        private string numerPeselField;
        
        private System.DateTime dataZapytaniaField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string numerPesel
        {
            get
            {
                return this.numerPeselField;
            }
            set
            {
                this.numerPeselField = value;
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="date", Order=1)]
        public System.DateTime dataZapytania
        {
            get
            {
                return this.dataZapytaniaField;
            }
            set
            {
                this.dataZapytaniaField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://uprawnieniakierowcow-na-date-zu.tru.api.cepik.coi.gov.pl")]
    public partial class DaneDokumentuRequest
    {
        
        private object itemField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("daneOsoby", typeof(DaneOsoby), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("danePesel", typeof(DanePesel), Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public object Item
        {
            get
            {
                return this.itemField;
            }
            set
            {
                this.itemField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://uprawnieniakierowcow-na-date-zu.tru.api.cepik.coi.gov.pl", ConfigurationName="ServiceReference1.UprawnieniaKierowcowNaDateZuUdoWS")]
    public interface UprawnieniaKierowcowNaDateZuUdoWS
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="", ReplyAction="*")]
        [System.ServiceModel.FaultContractAttribute(typeof(Komunikat[]), Action="", Name="cepikException", Namespace="http://exceptions.api.cepik.coi.gov.pl")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        System.Threading.Tasks.Task<DaneDokumentuResponse1> pytanieOUprawnieniaNaDateZUAsync(DaneDokumentuRequest1 request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DaneDokumentuRequest1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://uprawnieniakierowcow-na-date-zu.tru.api.cepik.coi.gov.pl", Order=0)]
        public DaneDokumentuRequest DaneDokumentuRequest;
        
        public DaneDokumentuRequest1()
        {
        }
        
        public DaneDokumentuRequest1(DaneDokumentuRequest DaneDokumentuRequest)
        {
            this.DaneDokumentuRequest = DaneDokumentuRequest;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DaneDokumentuResponse1
    {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://uprawnieniakierowcow-na-date-zu.tru.api.cepik.coi.gov.pl", Order=0)]
        public DaneDokumentuResponse DaneDokumentuResponse;
        
        public DaneDokumentuResponse1()
        {
        }
        
        public DaneDokumentuResponse1(DaneDokumentuResponse DaneDokumentuResponse)
        {
            this.DaneDokumentuResponse = DaneDokumentuResponse;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public interface UprawnieniaKierowcowNaDateZuUdoWSChannel : UprawnieniaKierowcowNaDateZuUdoWS, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "8.0.0")]
    public partial class UprawnieniaKierowcowNaDateZuUdoWSClient : System.ServiceModel.ClientBase<UprawnieniaKierowcowNaDateZuUdoWS>, UprawnieniaKierowcowNaDateZuUdoWS
    {
        
        public UprawnieniaKierowcowNaDateZuUdoWSClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<DaneDokumentuResponse1> UprawnieniaKierowcowNaDateZuUdoWS.pytanieOUprawnieniaNaDateZUAsync(DaneDokumentuRequest1 request)
        {
            return base.Channel.pytanieOUprawnieniaNaDateZUAsync(request);
        }

        public System.Threading.Tasks.Task<DaneDokumentuResponse1> pytanieOUprawnieniaNaDateZUAsync(DaneDokumentuRequest DaneDokumentuRequest)
        {
            DaneDokumentuRequest1 inValue = new DaneDokumentuRequest1();
            inValue.DaneDokumentuRequest = DaneDokumentuRequest;
            return ((UprawnieniaKierowcowNaDateZuUdoWS)(this)).pytanieOUprawnieniaNaDateZUAsync(inValue);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        #if !NET6_0_OR_GREATER
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        #endif
    }
}
